ZeroHunger/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ZeroHunger.DTOs;
using ZeroHunger.EF;

namespace ZeroHunger.Controllers
{

    public class AdminController : Controller
    {
        ZeroHungerContext db = new ZeroHungerContext();


        [HttpGet]
        public IActionResult Login()
        {
            return View(new AdminDTO());
        }

        [HttpPost]
        public IActionResult Login(AdminDTO adminLogin)
        {
            if (adminLogin.Email == null || adminLogin.Password == null)
            {
                ViewBag.ErrMsg = "Please fill up the form properly";
                return View(adminLogin);
            }

            var admin = (from a in db.Admins where a.Email.Equals(adminLogin.Email) && a.Password.Equals(adminLogin.Password) select a).SingleOrDefault();

            if (admin == null)
            {
                ViewBag.ErrMsg = "Incorrect Email or Password. Please try again.";
                return View(adminLogin);
            }

            HttpContext.Session.SetString("AdminId", admin.AdminId.ToString());
            return RedirectToAction("Dashboard");
        }

        [AdminAccess]
        public IActionResult Dashboard()
        {
            return View();
        }


        [HttpGet]
        [AdminAccess]
        public IActionResult AddEmployee()
        {
            return View(new EmployeeDTO());
        }

        [HttpPost]
        [AdminAccess]
        public IActionResult AddEmployee(EmployeeDTO emp)
        {
            if (ModelState.IsValid)
            {
                db.Employees.Add(EmployeeController.Convert(emp));
                db.SaveChanges();

                return RedirectToAction("AllEmployees");
            }

            return View(emp);
        }

        [AdminAccess]
        public IActionResult AllEmployees()
        {
            var employees = db.Employees.Include(e => e.Requests).ToList();
            return View(employees);
        }

        [AdminAccess]
        public IActionResult AllRestaurants()
        {
            var restaurants = db.Restaurants.Include(r => r.Requests).ToList();
            return View(restaurants);
        }

        [AdminAccess]
        public IActionResult AllRequests()
        {
            var requests = db.Requests.Include(r => r.Res).Include(r => r.Emp).ToList();
            return View(requests);
        }

        [AdminAccess]
        public IActionResult RequestDetails(int id)
        {
            var employees = db.Employees.ToList();
            ViewBag.Employees = employees;

            Request request = db.Requests
                            .Include(r => r.Emp)
                            .Include(r => r.Res)
                            .Include(r => r.Foods)
                            .SingleOrDefault(r => r.ReqId == id);

            return View(request);
        }

        [HttpPost]
        [AdminAccess]
        public IActionResult AssignEmp(int reqId, int empId)
        {
            if(empId != 1)
            {
                var req = db.Requests.Find(reqId);

                req.EmpId = empId;
                req.Status = "Assigned";

                db.SaveChanges();
            }
            return RedirectToAction("AllRequests");
        }

        [AdminAccess]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }
    }
}

ZeroHunger/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ZeroHunger.DTOs;
using ZeroHunger.EF;

namespace ZeroHunger.Controllers
{
    public class EmployeeController : Controller
    {
        ZeroHungerContext db = new ZeroHungerContext();

        [HttpGet]
        public IActionResult Login()
        {
            return View(new EmployeeDTO());
        }

        [HttpPost]
        public IActionResult Login(EmployeeDTO empLogin)
        {
            if (empLogin.Email == null || empLogin.Password == null)
            {
                ViewBag.ErrMsg = "Please fill up the form properly";
                return View(empLogin);
            }


            var employee = (from emp in db.Employees where emp.Email.Equals(empLogin.Email) && emp.Password.Equals(empLogin.Password) select emp).SingleOrDefault();

            if (employee == null)
            {
                ViewBag.ErrMsg = "Incorrect Email or Password. Please try again.";
                return View(empLogin);
            }

            HttpContext.Session.SetString("EmpId", employee.EmpId.ToString());
            return RedirectToAction("Dashboard");
        }

        [EmployeeAccess]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Login");
        }

        [EmployeeAccess]
        public IActionResult Dashboard()
        {
            var empId = Int32.Parse(HttpContext.Session.GetString("EmpId"));

            var requests = (from req in db.Requests where req.EmpId == empId select req).ToList();

            return View(RestaurantController.Convert(requests));
        }

        [EmployeeAccess]
        public IActionResult RequestDetails(int id)
        {
            Request request = db.Requests
                            .Include(r => r.Emp)
                            .Include(r => r.Res)
                            .Include(r => r.Foods)
                            .SingleOrDefault(r => r.ReqId == id);

            return View(request);
        }


        [HttpGet]
        [EmployeeAccess]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [EmployeeAccess]
        public IActionResult ChangePassword(string oldPass, string newPass)
        {
            if (oldPass == null || newPass == null)
            {
                ViewBag.ErrMsg = "Please fill up the form properly";
                return View();
            }

            var resId = Int32.Parse(HttpContext.Session.GetString("EmpId"));

            var employee = db.Employees.Find(resId);
            if (employee.Password == oldPass)
            {
                employee.Password = newPass;
                db.SaveChanges();
                return RedirectToAction("Dashboard");
            }
            else
            {
                ViewBag.ErrMsg = "Incorrect password";
                return View();
            }

        }

        [EmployeeAccess]
        public IActionResult Collected(int id)
        {
            var request = db.Requests.Find(id);
            request.Status = "Collected";
            request.CollectTime = DateTime.Now;
            db.SaveChanges();

            return RedirectToAction("Dashboard");
        }

        [HttpPost]
        [EmployeeAccess]
        public IActionResult Completed(int reqId, float totalCost)
        {
            if(totalCost > 0)
            {
                var request = db.Requests.Find(reqId);
                request.Status = "Completed";
                request.TotalCost = totalCost;
                request.CompleteTime = DateTime.Now;
                db.SaveChanges();
            }
            return RedirectToAction("Dashboard");
        }


        public static Employee Convert(EmployeeDTO emp)
        {
            return new Employee
            {
                EmpId = emp.EmpId,
                EmpName = emp.EmpName,
                Email = emp.Email,
                Password = emp.Password,
                Salary = emp.Salary,
                Address = emp.Address,
            };
        }
    }
}

ZeroHunger/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.Json;
using ZeroHunger.DTOs;
using ZeroHunger.EF;

namespace ZeroHunger.Controllers
{
    public class RestaurantController : Controller
    {
        ZeroHungerContext db = new ZeroHungerContext();


        [HttpGet]
        public IActionResult Login()
        {
            return View(new RestaurantDTO());
        }

        [HttpPost]
        public IActionResult Login(RestaurantDTO resLogin)
        {
            if(resLogin.Email == null || resLogin.Password == null)
            {
                ViewBag.ErrMsg = "Please fill up the form properly";
                return View(resLogin);
            }

            var restaurant = (from res in db.Restaurants where res.Email.Equals(resLogin.Email) && res.Password.Equals(resLogin.Password) select res).SingleOrDefault();

            if(restaurant == null)
            {
                ViewBag.ErrMsg = "Incorrect Email or Password. Please try again.";
                return View(resLogin);
            }

            HttpContext.Session.SetString("ResId", restaurant.ResId.ToString());
            return RedirectToAction("Dashboard");
        }


        [HttpGet]
        public IActionResult Signup()
        {
            return View(new RestaurantDTO());
        }

        [HttpPost]
        public IActionResult Signup(RestaurantDTO resSignup)
        {
            if(ModelState.IsValid)
            {
                Restaurant res = Convert(resSignup);
                db.Restaurants.Add(res);
                db.SaveChanges();

                HttpContext.Session.SetString("ResId", res.ResId.ToString());
                return RedirectToAction("Dashboard");
            }

            return View(resSignup);
        }


        [RestaurantAccess]
        public IActionResult Dashboard()
        {
            var resId = Int32.Parse(HttpContext.Session.GetString("ResId"));

            var requests = (from req in db.Requests where req.ResId == resId select req).ToList();
            return View(Convert(requests));
        }


        [RestaurantAccess]
        public IActionResult RequestDetails(int id)
        {
            // Request request = db.Requests.Find(id);
            Request request = db.Requests
                            .Include(r => r.Emp)
                            .Include(r => r.Res)
                            .Include(r => r.Foods)
                            .SingleOrDefault(r => r.ReqId == id);

            return View(request);
        }

        [HttpGet]
        [RestaurantAccess]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        [RestaurantAccess]
        public IActionResult ChangePassword(string oldPass, string newPass)
        {
            if (oldPass == null || newPass == null)
            {
                ViewBag.ErrMsg = "Please fill up the form properly";
                return View();
            }

            var resId = Int32.Parse(HttpContext.Session.GetString("ResId"));

            var restaurant = db.Restaurants.Find(resId);

            if(restaurant.Password == oldPass)
            {
                restaurant.Password = newPass;
                db.SaveChanges();
                ViewBag.SuccessMsg = "Password changed Successfully";
                return View();
            }
            else
            {
                ViewBag.ErrMsg = "Incorrect password";
                return View();
            }

        }


        [HttpGet]
        [RestaurantAccess]
        public IActionResult AddFood()
        {
            return View(new FoodDTO());
        }

        [HttpPost]
        [RestaurantAccess]
        public IActionResult AddFood(FoodDTO food)
        {
            if (ModelState.IsValid)
            {
                List<FoodDTO> foods = null;
                var sessionData = HttpContext.Session.GetString("Foods");

                if(sessionData == null)
                {
                    foods = new List<FoodDTO>();
                }
                else
                {
                    foods = JsonSerializer.Deserialize<List<FoodDTO>>(sessionData);
                }

                foods.Add(food);

                var jsonData = JsonSerializer.Serialize(foods);
                HttpContext.Session.SetString("Foods", jsonData);

                return RedirectToAction("CreateRequest");
            }

            return View(food);
        }

        [RestaurantAccess]
        public IActionResult RemoveFood(string foodName, int quantity)
        {
            var sessionData = HttpContext.Session.GetString("Foods");
            var foods = JsonSerializer.Deserialize<List<FoodDTO>>(sessionData);

            var food = (from f in foods where f.FoodName == foodName && f.Quantity == quantity select f).SingleOrDefault();

            foods.Remove(food);

            var jsonData = JsonSerializer.Serialize(foods);
            HttpContext.Session.SetString("Foods", jsonData);

            return RedirectToAction("CreateRequest");
        }

        [RestaurantAccess]
        public IActionResult CreateRequest()
        {
            List<FoodDTO> foods = null;
            var sessionData = HttpContext.Session.GetString("Foods");

            if (sessionData == null)
            {
                foods = new List<FoodDTO>();
            }
            else
            {
                foods = JsonSerializer.Deserialize<List<FoodDTO>>(sessionData);
            }

            return View(foods);
        }

        [HttpGet]
        [RestaurantAccess]
        public IActionResult ConfirmRequest()
        {
            return View();
        }

        [HttpPost]
        [RestaurantAccess]
        public IActionResult ConfirmRequest(DateTime preTime)
        {
            if(preTime >= DateTime.Now)
            {
                Request request = new Request();
                request.ResId = Int32.Parse(HttpContext.Session.GetString("ResId"));
                request.ReqTime = DateTime.Now;
                request.PreserveTime = preTime;
                request.EmpId = 1;
                request.Status = "Requested";
                request.TotalCost = 0;

                db.Requests.Add(request);
                db.SaveChanges();


                var sessionData = HttpContext.Session.GetString("Foods");
                var foods = JsonSerializer.Deserialize<List<FoodDTO>>(sessionData);

                foreach(var food in foods)
                {
                    var f = new Food();
                    f.FoodName = food.FoodName;
                    f.Quantity = food.Quantity;
                    f.ReqId = request.ReqId;

                    db.Foods.Add(f);
                }
                db.SaveChanges();

                HttpContext.Session.Remove("Foods");
                return RedirectToAction("Dashboard");
            }

            ViewBag.ErrMsg = "Please select a date time";
            return View();
        }



        public static Restaurant Convert (RestaurantDTO res)
        {
            return new Restaurant
            {
                ResId = res.ResId,
                ResName = res.ResName,
                Email = res.Email,
                Password = res.Password,
                Address = res.Address,
            };
        }

        public static Request Convert(RequestDTO req)
        {
            return new Request
            {
                ReqId = req.ReqId,
                ResId = req.ResId,
                ReqTime = req.ReqTime,
                PreserveTime = req.PreserveTime,
                EmpId = req.EmpId,
                CollectTime = req.CollectTime,
                CompleteTime = req.CompleteTime,
                Status = req.Status,
                TotalCost = req.TotalCost,
            };
        }

        public static RequestDTO Convert(Request req)
        {
            return new RequestDTO
            {
                ReqId = req.ReqId,
                ResId = req.ResId,
                ReqTime = req.ReqTime,
                PreserveTime = req.PreserveTime,
                EmpId = req.EmpId,
                CollectTime = req.CollectTime,
                CompleteTime = req.CompleteTime,
                Status = req.Status,
                TotalCost = req.TotalCost,
            };
        }

        public static List<RequestDTO> Convert(List<Request> data)
        {
            var list = new List<RequestDTO>();
            foreach (var item in data)
            {
                list.Add(Convert(item));
            }
            return list;
        }

    }
}

ZeroHunger/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ZeroHunger.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Dashboard">ZeroHunger</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark text-decoration-underline" asp-area="" asp-controller="Admin" asp-action="AddEmployee">Add Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark text-decoration-underline" asp-area="" asp-controller="Admin" asp-action="AllEmployees">All Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark text-decoration-underline" asp-area="" asp-controller="Admin" asp-action="AllRestaurants">All Restaurants</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark text-decoration-underline" asp-area="" asp-controller="Admin" asp-action="AllRequests">All Requests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ZeroHunger - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ZeroHunger/Views/Shared/_EmployeeLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ZeroHunger.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Employee" asp-action="Dashboard">ZeroHunger</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="ChangePassword">Change Password</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ZeroHunger - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ZeroHunger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ZeroHunger.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ZeroHunger</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Restaurant" asp-action="Login">Restaurant Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Login">Employee Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Login">Admin Login</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ZeroHunger - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ZeroHunger/Views/Shared/_RestaurantLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ZeroHunger.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Restaurant" asp-action="Dashboard">ZeroHunger</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark text-decoration-underline" asp-area="" asp-controller="Restaurant" asp-action="AddFood">Add Food To Request</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark text-decoration-underline" asp-area="" asp-controller="Restaurant" asp-action="CreateRequest">Create Request</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark text-decoration-underline" asp-area="" asp-controller="Restaurant" asp-action="ChangePassword">Change Password</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ZeroHunger - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>